/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uipacontroleadotantes.gui;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import uipacontroleadotantes.banco.usuarios.UsuariosBean;
import uipacontroleadotantes.banco.usuarios.UsuariosDAO;
import uipacontroleadotantes.uteis.Sanitize;
import uipacontroleadotantes.uteis.Seguranca;

/**
 *
 * @author mckatoo
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    final private BioGUI bioGui = new BioGUI();
    public LoginGUI() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/uipacontroleadotantes/assets/logo.jpg")).getImage());
        this.setLocationRelativeTo(null);
//        Color color = new Color(238, 238, 238, 250);
//        userIcon.setLocation((this.getWidth() / 2) - (userIcon.getWidth() / 2), 30);
//        jPanel1.setBackground(color);
//        jPanel1.setLocation((this.getWidth() / 2) - (jPanel1.getWidth() / 2), 250);
//        btnFechar.setLocation(this.getWidth() - btnFechar.getWidth() - 10, 10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        userIcon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        cbBio = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UIPA - Controle de Adotantes");
        setFont(new java.awt.Font("aakar", 0, 10)); // NOI18N
        setMinimumSize(new java.awt.Dimension(350, 400));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(350, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(350, 400));
        getContentPane().setLayout(null);

        btnFechar.setBackground(new java.awt.Color(255, 51, 51));
        btnFechar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(255, 255, 255));
        btnFechar.setText("X");
        btnFechar.setBorder(null);
        btnFechar.setFocusable(false);
        btnFechar.setIconTextGap(0);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar);
        btnFechar.setBounds(310, 10, 30, 30);

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uipacontroleadotantes/assets/user-branco.png"))); // NOI18N
        userIcon.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        userIcon.setIconTextGap(0);
        getContentPane().add(userIcon);
        userIcon.setBounds(110, 50, 150, 130);

        jLabel2.setText("Usuário:");

        txtUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });

        jLabel3.setText("Senha:");

        btnEntrar.setBackground(new java.awt.Color(255, 51, 51));
        btnEntrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        btnEntrar.setEnabled(false);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        txtSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSenhaKeyReleased(evt);
            }
        });

        cbBio.setText("Entar usando Biometria");
        cbBio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario)
                            .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbBio)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbBio)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 210, 330, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uipacontroleadotantes/assets/fundo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        dispose();
        final Loading loading = new Loading();

        CompletableFuture.runAsync(() -> {
            final LoginGUI loginGUI = this;
            Point p = this.getLocation();

            PrincipalGUI principal = new PrincipalGUI();
            UsuariosDAO usuariosDAO = new UsuariosDAO();

            if (usuariosDAO.count() == 0) {
                UsuariosBean usuarioBean = new UsuariosBean();
                usuarioBean.setLogin("uipa");
                usuarioBean.setSenha("uipa");
                try {
                    usuariosDAO.inserir(usuarioBean);
                } catch (SQLException ex) {
                    Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            String senha = Sanitize.sanitizar(txtSenha.getPassword());
            String senhaCriptografada = Seguranca.criptografar(senha);
            Future<Boolean> future = usuariosDAO.login(txtUsuario.getText(), senhaCriptografada);
            Boolean permitido = false;
            while (!future.isDone()) {
                System.out.println("VERIFICANDO CREDÊNCIAIS...");
            }
            System.out.println("CREDÊNCIAIS ACEITAS.");
            try {
                permitido = future.get(10, TimeUnit.SECONDS);
            } catch (InterruptedException | ExecutionException | TimeoutException ex) {
                JOptionPane.showMessageDialog(null, "ERRO: " + ex.getMessage());
            }
            loading.dispose();
            if (permitido) {
                dispose();
                principal.setVisible(true);
            } else {
                loginGUI.setVisible(true);
                new Thread() {
                    @Override
                    public void run() {
                        try {
                            for (int i = 0; i < 3; i++) {
                                loginGUI.setLocation(p.x - 10, p.y);
                                sleep(20);
                                loginGUI.setLocation(p.x + 10, p.y);
                                sleep(20);
                            }
                        } catch (InterruptedException ex) {
                            Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }.start();
                JOptionPane.showMessageDialog(null, "USUÁRIO OU SENHA INVÁLIDOS!");
            }
        });

    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void txtSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnEntrar.doClick();
        }
        filledData();
    }//GEN-LAST:event_txtSenhaKeyReleased

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed

    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtSenha.requestFocus();
        }
        filledData();
    }//GEN-LAST:event_txtUsuarioKeyReleased

    private void filledData() {
        if (txtSenha.getPassword().length > 0 & txtUsuario.getText().length() > 0) {
            btnEntrar.setEnabled(true);
            btnEntrar.setEnabled(true);
        } else {
            btnEntrar.setEnabled(false);
            btnEntrar.setEnabled(false);
        }
    }

    private void cbBioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBioActionPerformed
        jLabel2.setEnabled(!cbBio.isSelected());
        txtUsuario.setEnabled(!cbBio.isSelected());
        txtUsuario.setEditable(!cbBio.isSelected());
        jLabel3.setEnabled(!cbBio.isSelected());
        txtSenha.setEnabled(!cbBio.isSelected());
        txtSenha.setEditable(!cbBio.isSelected());
        if (txtUsuario.getText().length() > 0 & txtSenha.getPassword().length > 0) {
            btnEntrar.setEnabled(!cbBio.isSelected());
        }
        bioGui.setVisible(cbBio.isSelected());
    }//GEN-LAST:event_cbBioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JCheckBox cbBio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
